### ISSUE TITLE
lang error

### ISSUE THREAD

**Issue by xiaoxi654** [AtoxSplash/Meth-manager#3]
![screenshot](https://i.loli.net/2019/07/13/5d29acbdca96823805.png)
I got this error in my playing, my language is Simplified Chinese

**Comment by FR0Z3** [comment]
已通知作者，顺便不太清楚是不是因为联合汉化的原因em。 顺便我Steam 连接的话 https://steamcommunity.com/id/EAM_F0RZ3 ，我会注意一下加我的ID的。

**Comment by xiaoxi654** [comment]
> 已通知作者，顺便不太清楚是不是因为联合汉化的原因em。 顺便我Steam 连接的话 https://steamcommunity.com/id/EAM_F0RZ3 ，我会注意一下加我的ID的。

值得一提的是，这个情况在使用之前版本没有本地化的时候也一样，可能真的是和汉化不兼容？

**Comment by FR0Z3** [comment]
> > 已通知作者，顺便不太清楚是不是因为联合汉化的原因em。 顺便我Steam 连接的话 https://steamcommunity.com/id/EAM_F0RZ3 ，我会注意一下加我的ID的。
> 
> 值得一提的是，这个情况在使用之前版本没有本地化的时候也一样，可能真的是和汉化不兼容？

我想可能是吧。

**Comment by FR0Z3** [comment]
作者应该在解决了，好了之后再试着下载吧
Edit: 顺便我把 PDLG 汉化也给了作者，希望可以添加语言选择吧

**Comment by xiaoxi654** [comment]
在 #5 中修复，发现是一个小的拼写错误
